accelerate launch accel.py \
    --model_name_or_path gpt2 \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 4 \
    --do_train \
    --fp16 \
    --seed 42 \
    --logging_dir logs \
    --overwrite_output_dir \
    --output_dir test-clm 
